export const fishTypesArray = ["ANGLER FISH"
,"BASS"
,"BREAM - Black"
,"BREAM - Gilthead"
,"BREAM - Red"
,"BRILL"
,"BULL HUSS"
,"CATFISH"
,"CONGER EEL"
,"COALFISH"
,"COD"
,"DAB"
,"FLOUNDER"
,"GARFISH"
,"GURNARD - Red"
,"GURNARD - Tub"
,"HADDOCK"
,"JOHN DORY"
,"LESSER SPOTTED DOGFISH"
,"LING"
,"MACKEREL"
,"MEGRIM"
,"MONKFISH"
,"MULLET - Golden Grey"
,"MULLET - Red"
,"MULLET - Thick Lipped"
,"MULLET - Thin Lipped"
,"PLAICE"
,"POLLACK"
,"POUTING"
,"RAY - Blonde"
,"RAY - Small Eyed/Painted"
,"RAY - Spotted/Homelyn"
,"RAY - Sting"
,"RAY - Thornback"
,"RAY - Undulate"
,"ROCKLING - 3 Bearded"
,"SCAD"
,"SILVER EEL"
,"SMOOTHHOUNDS - All"
,"SOLE"
,"SPURDOG"
,"TOPE"
,"TRIGGER FISH"
,"TURBOT"
,"WEEVER - Greater"
,"WHITING"
,"WRASSE - Ballan"
,"WRASSE - Cuckoo"]as const

export function isFishType(str :string) : str is FishType {
    return fishTypesArray.includes(str as FishType);
}

export type FishType  = typeof fishTypesArray[number]

export {}